name: Lint & Test
on:
  pull_request:
  push:
    branches:
      - master

env:
  CGO_ENABLED: 1

jobs:
  test:
    uses: SiaFoundation/workflows/.github/workflows/go-test.yml@dddded471aae1c7b6f0fbc388d603b8b16336f6f # master

  postgres:
    name: Test (postgres)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      POSTGRES_USER: explored_test
      POSTGRES_PASSWORD: explored_test
      POSTGRES_DB: explored_test
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: explored_test
          POSTGRES_PASSWORD: explored_test
          POSTGRES_DB: explored_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: "1.26"
      - name: Test
        uses: n8maninger/action-golang-test@aa292dc81b16d34406a9551e629e0cdca00d9418 # v2.2.1
        with:
          args: -race;-failfast;-tags=postgres,testing
