name: Publish OpenAPI to Scalar Registry

permissions:
  contents: read

on:
  push:
    branches: [ master ]
    paths:
      - "openapi.yml"
  workflow_dispatch:

jobs:
  publish:
    uses: SiaFoundation/workflows/.github/workflows/publish-openapi.yml@master
    with:
      slug: explored
      spec_path: openapi.yml
      docs_slug: explored
    secrets:
      SCALAR_API_KEY: ${{ secrets.SCALAR_API_KEY }}
